# 1. H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 2. Database URL z blokad? zamykania bazy
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 3. Hibernate - niech on stworzy tabele na podstawie Twoich klas Java (Entity)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# 4. SQL Data - kluczowe ustawienia dla data.sql
# Zawsze wykonuj data.sql
spring.sql.init.mode=always
# Czekaj z wykonaniem data.sql, a? Hibernate stworzy struktur? tabel
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl